// ══════════ DATA: Events ══════════
const EVENTS = [
  {id:1,type:"team",emoji:"🛠️",name:"Animatronics",tagline:"Build a robotic display featuring motion, sound, and programming.",desc:"Teams create an animatronic device that demonstrates engineering, control, and storytelling for judges.",rules:["3 teams of 2-3 members per state","Must include motion and a control system","Judged on engineering, creativity, and reliability"],tips:["Design mechanisms that are simple and reliable","Proof each motion sequence before final assembly","Plan wiring and programming early"],participants:"3 teams of 2-3 per state",duration:"On-site demonstration"},
  {id:2,type:"team",emoji:"🏛️",name:"Architectural Design",tagline:"Design a building solution with plans, elevations, and narrative.",desc:"Teams prepare a portfolio documenting an architectural project and explain how it meets client and site requirements.",rules:["1 team per chapter; individual entries are permitted","Must submit annotated drawings and supporting rationale","Judged on creativity, feasibility, and presentation"],tips:["Show clear site planning and floor layouts","Label drawings and include dimensions","Explain how your design solves the problem"],participants:"1 team per chapter; individual entries permitted",duration:"Portfolio + interview"},
  {id:3,type:"team",emoji:"🎙️",name:"Audio Podcasting",tagline:"Produce a short podcast episode on a STEM or tech topic.",desc:"Teams record, edit, and submit a podcast demonstrating effective storytelling and audio quality.",rules:["3 teams per state; individual entries are permitted","Must meet length and audio quality requirements","Judged on content, creativity, and production"],tips:["Write a tight script and plan segments","Use clear audio and edit out distractions","Create a memorable opening and close"],participants:"3 teams per state; individual entries permitted",duration:"Pre-event submission"},
  {id:4,type:"team",emoji:"🧬",name:"Biotechnology Design",tagline:"Develop a biotech innovation that addresses a real challenge.",desc:"Teams create a portfolio describing a biotechnology solution, research, and ethical considerations.",rules:["1 team of at least 2 individuals per chapter","Must include research, prototype concept, and analysis","Judged on science, design, and clarity"],tips:["Explain your biotech concept with clear visuals","Discuss safety and ethical impact","Use current science to support your design"],participants:"1 team of 2+ per chapter",duration:"Portfolio + interview"},
  {id:5,type:"team",emoji:"🎲",name:"Board Game Design",tagline:"Create an original board game that teaches or explores technology.",desc:"Teams design a playable board game with rules, components, and narrative focused on a tech theme.",rules:["1 team of at least 2 individuals per chapter","Must submit a game board, pieces, and written rules","Judged on design, creativity, and playability"],tips:["Keep the rules simple and easy to follow","Balance game mechanics for fair play","Include strong theme integration"],participants:"1 team of 2+ per chapter",duration:"Portfolio + playtest"},
  {id:6,type:"chapter",emoji:"🏆",name:"Chapter Team",tagline:"Present a prepared performance highlighting your chapter's strengths.",desc:"Each chapter performs a prepared team show that demonstrates technology, teamwork, and pride.",rules:["1 team of 6 members per chapter","Must be a prepared, timed performance","Judged on creativity, execution, and chapter spirit"],tips:["Assign roles clearly and rehearse often","Use technology in a way that supports your story","Keep the show polished and on time"],participants:"1 team of 6 per chapter",duration:"Timed performance"},
  {id:7,type:"team",emoji:"📚",name:"Children's Stories",tagline:"Write and present a story that shares a STEM message for young readers.",desc:"Teams or individuals create a story that conveys a technology theme in an engaging, child-friendly format.",rules:["3 teams or 3 individuals per state","Must submit a written story and visual support","Judged on creativity, clarity, and theme"],tips:["Craft a strong narrative with a clear STEM message","Use language appropriate for children","Include illustrations or visuals to support the story"],participants:"3 teams or 3 individuals per state",duration:"Pre-event submission"},
  {id:8,type:"team",emoji:"💻",name:"Coding",tagline:"Solve algorithmic problems using clean, efficient code.",desc:"Teams write programs during a timed event, demonstrating logic, correctness, and efficiency.",rules:["3 teams of 2 individuals per state","Work independently during the coding session","Judged on correctness, efficiency, and style"],tips:["Practice algorithmic problem solving with timed drills","Keep code readable and well-structured","Test edge cases before submitting"],participants:"3 teams of 2 per state",duration:"Timed coding"},
  {id:9,type:"individual",emoji:"🏙️",name:"Computer-Aided Design (CAD), Architecture",tagline:"Use CAD tools to model an architectural design solution.",desc:"Individuals create detailed CAD drawings and models for an architecture-related problem.",rules:["2 individuals per state","Must submit CAD files and technical drawings","Judged on accuracy, presentation, and design quality"],tips:["Organize CAD files with clear layer naming","Include dimensions and annotations","Render drawings neatly for judges"],participants:"2 individuals per state",duration:"Portfolio + modeling"},
  {id:10,type:"individual",emoji:"🧰",name:"Computer-Aided Design (CAD), Engineering",tagline:"Model engineering solutions with CAD documentation.",desc:"Individuals produce CAD drawings and documentation for a technical engineering prompt.",rules:["2 individuals per state","Submit CAD files and supporting drawings","Judged on precision, presentation, and design"],tips:["Double-check all dimensions and constraints","Use good CAD practices for clarity","Include optional renderings when possible"],participants:"2 individuals per state",duration:"Portfolio + modeling"},
  {id:11,type:"team",emoji:"📊",name:"Data Science and Analytics",tagline:"Analyze data and present insights using analytics tools.",desc:"Teams explore datasets to answer questions and recommend solutions with charts and analysis.",rules:["3 teams of 2 individuals per state; individual entries are permitted","Must use provided datasets and support findings with evidence","Judged on accuracy, insight, and presentation"],tips:["Clean your data before analysis","Use clear visualizations to support conclusions","Explain why your recommendations matter"],participants:"3 teams of 2 per state; individual entries permitted",duration:"Portfolio + presentation"},
  {id:12,type:"team",emoji:"🗣️",name:"Debating Technological Issues",tagline:"Debate a technology issue with research and persuasive arguments.",desc:"Teams prepare and present arguments on a current technology topic, responding to judge questions.",rules:["3 teams of 2 individuals per state","Must follow debate format and time limits","Judged on argument quality, research, and delivery"],tips:["Research both sides of the issue thoroughly","Practice clear rebuttals and transitions","Speak confidently and stay organized"],participants:"3 teams of 2 per state",duration:"Timed debate"},
  {id:13,type:"team",emoji:"🎬",name:"Digital Video Production",tagline:"Produce a short video that communicates a STEM story.",desc:"Teams develop, shoot, and edit a video that explains or promotes a technology topic.",rules:["3 teams or 3 individuals per state","Must meet length and technical requirements","Judged on storytelling, production, and creativity"],tips:["Create a storyboard before filming","Use clear audio and concise edits","Keep visuals aligned with your message"],participants:"3 teams or 3 individuals per state",duration:"Pre-event submission"},
  {id:14,type:"team",emoji:"🏎️",name:"Dragster Design",tagline:"Engineer and race a CO₂-powered dragster for speed and design.",desc:"Teams build, present, and race a dragster, combining engineering documentation with performance.",rules:["2 individuals per chapter","Must meet official size limits","Judged on speed, craftsmanship, and documentation"],tips:["Polish axles and bearings for less friction","Keep the design aerodynamic and balanced","Document your build process clearly"],participants:"2 individuals per chapter",duration:"On-site race"},
  {id:15,type:"team",emoji:"🛩️",name:"Drone Challenge (UAV)",tagline:"Design and fly an unmanned aerial vehicle for a set challenge.",desc:"Teams build and program a drone to complete tasks safely and accurately.",rules:["3 teams of 2-6 members per state","Must follow flight safety and challenge rules","Judged on design, performance, and control"],tips:["Test flight controls in a safe environment","Choose reliable motors and batteries","Plan your mission strategy before the event"],participants:"3 teams of 2-6 per state",duration:"On-site flight"},
  {id:16,type:"team",emoji:"🧰",name:"Engineering Design",tagline:"Develop a complete engineering solution from research to recommendation.",desc:"Teams create a design portfolio documenting problem solving, planning, and final solutions.",rules:["3 teams of 3+ individuals per state","Must submit a thorough design portfolio","Judged on process, innovation, and presentation"],tips:["Show every stage of your design process","Use clear diagrams and prototypes","Explain how your solution meets constraints"],participants:"3 teams of 3+ per state",duration:"Portfolio + interview"},
  {id:17,type:"individual",emoji:"🎤",name:"Extemporaneous Speech",tagline:"Speak on a STEM topic with only 30 minutes to prepare.",desc:"Individuals draw a technology-related topic and deliver a polished speech after brief preparation.",rules:["3 individuals per state","30 minutes of prep; no internet access","Speech must be 3-5 minutes"],tips:["Practice organizing ideas quickly","Use a simple structure with a strong opening","Speak clearly and confidently"],participants:"3 individuals per state",duration:"3-5 min speech"},
  {id:18,type:"team",emoji:"👗",name:"Fashion Design and Technology",tagline:"Design wearable technology or smart fashion for a modern audience.",desc:"Teams create a fashion project that integrates technology in a creative, functional way.",rules:["5 teams of 2-4 individuals per state","Must include design and technology elements","Judged on innovation, style, and execution"],tips:["Sketch your concept and tech placement first","Choose materials that support your idea","Balance fashion and functionality"],participants:"5 teams of 2-4 per state",duration:"Portfolio + runway"},
  {id:19,type:"team",emoji:"✈️",name:"Flight Endurance",tagline:"Design and fly a model aircraft for maximum airtime.",desc:"Teams build an aircraft and compete for the longest stable flight duration.",rules:["2 individuals per chapter","Must meet size and safety limits","Judged on flight time and craftsmanship"],tips:["Optimize wing shape for lift","Balance weight and stability carefully","Test glides before the official flight"],participants:"2 individuals per chapter",duration:"On-site flight"},
  {id:20,type:"team",emoji:"🧪",name:"Forensic Science",tagline:"Analyze evidence and solve a crime scene problem scientifically.",desc:"Teams use forensic techniques to interpret data and answer investigative questions accurately.",rules:["1 team of 2 individuals per chapter","No outside assistance during the event","Judged on analysis, accuracy, and reasoning"],tips:["Practice evaluating evidence systematically","Know the terminology and methods","Show your reasoning clearly"],participants:"1 team of 2 per chapter",duration:"Timed exam"},
  {id:21,type:"individual",emoji:"🎓",name:"Future Technology and Engineering Teacher",tagline:"Create a teaching resource for a STEM or technology lesson.",desc:"Individuals design a lesson plan or teaching tool that promotes technology learning and engagement.",rules:["3 individuals per chapter","Must submit a teaching plan and visuals","Judged on clarity, pedagogy, and creativity"],tips:["Make your lesson easy to follow","Include student engagement activities","Use examples that connect to real technology"],participants:"3 individuals per chapter",duration:"Portfolio + presentation"},
  {id:22,type:"team",emoji:"🗺️",name:"Geospatial Technology",tagline:"Use spatial data and mapping to solve a real-world problem.",desc:"Teams analyze geographic information and present a solution using maps or GIS tools.",rules:["1 team of 2-3 individuals per chapter","Must submit maps, data analysis, and conclusions","Judged on accuracy, innovation, and presentation"],tips:["Organize your spatial data clearly","Choose the best map style for your story","Explain why your solution matters"],participants:"1 team of 2-3 per chapter",duration:"Portfolio + presentation"},
  {id:23,type:"team",emoji:"🏭",name:"Manufacturing Prototype",tagline:"Design and build a prototype for a manufacturing challenge.",desc:"Teams develop a prototype and documentation showing how it meets a production need.",rules:["1 team of 2+ individuals per chapter","Must submit a prototype design and process documentation","Judged on feasibility, innovation, and presentation"],tips:["Keep your prototype functional and testable","Document your manufacturing decisions clearly","Use realistic materials and processes"],participants:"1 team of 2+ per chapter",duration:"Portfolio + prototype"},
  {id:24,type:"team",emoji:"🎵",name:"Music Production",tagline:"Create a recorded music project that showcases technology and creativity.",desc:"Teams produce and submit a music track demonstrating production skills and originality.",rules:["3 teams per state; individual entries are permitted","Must meet audio quality and production guidelines","Judged on creativity, arrangement, and sound"],tips:["Plan your track before recording","Focus on a strong mix and clear vocals","Use technology to enhance your style"],participants:"3 teams per state; individual entries permitted",duration:"Pre-event submission"},
  {id:25,type:"team",emoji:"🎥",name:"On Demand Video",tagline:"Produce a short video that responds to an assigned prompt.",desc:"Teams create a complete video package following technical requirements and storytelling guidelines.",rules:["1 team of at least 2 individuals per chapter","Must meet timing and production requirements","Judged on content, craft, and creativity"],tips:["Write a strong storyboard first","Capture clean audio and compelling visuals","Edit tightly for pacing and clarity"],participants:"1 team of 2+ per chapter",duration:"Pre-event submission"},
  {id:26,type:"individual",emoji:"📷",name:"Photographic Technology",tagline:"Capture images that communicate technology and innovation.",desc:"Individuals submit a photography portfolio focused on a technology-related theme.",rules:["1 individual per chapter","Photos must be original work from the current year","Judged on composition, creativity, and theme"],tips:["Use strong lighting and composition","Tell a story through your images","Edit carefully for consistency"],participants:"1 individual per chapter",duration:"Pre-event submission"},
  {id:27,type:"individual",emoji:"📋",name:"Prepared Presentation",tagline:"Deliver a polished STEM presentation from a prepared prompt.",desc:"Individuals research and present an assigned topic using visuals and clear communication.",rules:["3 individuals per state","Must follow time limits and presentation rules","Judged on content, delivery, and visuals"],tips:["Create a logical presentation flow","Practice your delivery and timing","Use visuals to support, not replace, your talk"],participants:"3 individuals per state",duration:"8-10 min presentation"},
  {id:28,type:"individual",emoji:"🎨",name:"Promotional Design",tagline:"Design a visual campaign to promote a product or message.",desc:"Individuals create promotional materials that clearly communicate a product, service, or cause.",rules:["3 individuals per state","Must include design pieces and written justification","Judged on creativity, clarity, and visual impact"],tips:["Keep your layout clean and readable","Focus on a strong central message","Use a consistent visual style"],participants:"3 individuals per state",duration:"Portfolio + presentation"},
  {id:29,type:"team",emoji:"🤖",name:"Robotics",tagline:"Build and program a robot to complete technical tasks.",desc:"Teams design, build, and operate a robot that solves a challenge using mechanics and programming.",rules:["3 teams of 2-6 members per state","Must follow size, safety, and performance rules","Judged on design, execution, and strategy"],tips:["Practice each mission with consistent robot control","Build durable mechanisms for repeated use","Keep wiring tidy and reliable"],participants:"3 teams of 2-6 per state",duration:"On-site challenge"},
  {id:30,type:"team",emoji:"☀️",name:"Senior Solar Sprint",tagline:"Design and race a small solar-powered vehicle.",desc:"Teams build a solar car and compete for speed while demonstrating engineering design.",rules:["1 team of 2-4 individuals per chapter; one entry per team","Must meet solar and size requirements","Judged on speed, design, and craftsmanship"],tips:["Optimize solar panel angle and weight balance","Test under consistent light conditions","Polish moving parts to reduce friction"],participants:"1 team of 2-4 per chapter",duration:"On-site race"},
  {id:31,type:"team",emoji:"💻",name:"Software Development",tagline:"Develop a software application with a focus on usability and function.",desc:"Teams produce a software solution and supporting materials; presentation/interview is limited to three members.",rules:["1 team of 2+ individuals per chapter; presentation/interview limited to 3 members","Must submit working software and documentation","Judged on functionality, design, and presentation"],tips:["Plan your application before coding","Document features and user workflows clearly","Practice your demo with the team"],participants:"1 team of 2+ per chapter; presentation limited to 3",duration:"Portfolio + demo"},
  {id:32,type:"team",emoji:"📰",name:"STEM Mass Media",tagline:"Create a media project that communicates technology to a broad audience.",desc:"Teams develop a media package such as a newspaper, newsletter, or digital content focused on STEM topics.",rules:["1 team of 2-3 members per chapter","Must include original content and design","Judged on clarity, creativity, and media quality"],tips:["Publish strong headlines and visuals","Organize content for easy reading","Use technology stories that matter to your audience"],participants:"1 team of 2-3 per chapter",duration:"Portfolio + media"},
  {id:33,type:"team",emoji:"🧱",name:"Structural Design and Engineering",tagline:"Design and document a structure that meets engineering requirements.",desc:"Teams create a structural design solution and submit a portfolio showing calculations and drawings.",rules:["1 team of 2 individuals per chapter","Must provide technical drawings and analysis","Judged on design, accuracy, and presentation"],tips:["Use clear diagrams and labels","Explain how your structure handles loads","Check calculations carefully"],participants:"1 team of 2 per chapter",duration:"Portfolio + interview"},
  {id:34,type:"team",emoji:"⚙️",name:"System Control Technology",tagline:"Design a control system for a technical process or device.",desc:"Teams build and describe a system that monitors and controls a process using technology principles.",rules:["2 teams of 3 individuals per state","Must include system explanation and performance data","Judged on design, accuracy, and innovation"],tips:["Keep your control logic clear and documented","Test the system under multiple conditions","Show how the system maintains stability"],participants:"2 teams of 3 per state",duration:"Portfolio + demonstration"},
  {id:35,type:"team",emoji:"🧠",name:"Technology Bowl",tagline:"Compete as a chapter team in a fast-paced technology quiz.",desc:"Each chapter fields a team to answer technology knowledge questions in a competitive bowl format.",rules:["1 team of 3 individuals per chapter","Must follow official quiz rules","Judged on accuracy and speed"],tips:["Study core technology concepts thoroughly","Practice quick recall and teamwork","Communicate clearly during the bowl"],participants:"1 team of 3 per chapter",duration:"Timed quiz"},
  {id:36,type:"team",emoji:"📝",name:"Technology Problem Solving",tagline:"Solve an open-ended technology challenge as a chapter team.",desc:"Chapters submit a written problem solution and optional visuals for an assigned technical issue.",rules:["1 team of 2 individuals per chapter","Must submit a written report and supporting materials","Judged on reasoning, creativity, and clarity"],tips:["Organize your report with clear sections","Use visuals to support your solution","Proofread for clarity and completeness"],participants:"1 team of 2 per chapter",duration:"Written response"},
  {id:37,type:"individual",emoji:"🚗",name:"Transportation Modeling",tagline:"Build a model that illustrates transportation systems or innovations.",desc:"Individuals create a model and documentation that explain a transportation concept or design.",rules:["1 individual per chapter","Must include a physical model and supporting write-up","Judged on creativity, accuracy, and communication"],tips:["Make your model easy to understand","Explain how the transportation system works","Use visuals and labels effectively"],participants:"1 individual per chapter",duration:"Portfolio + model"},
  {id:38,type:"team",emoji:"🎮",name:"Video Game Design",tagline:"Design and build an original playable video game.",desc:"Teams create a game prototype and portfolio that explain gameplay, theme, and technical execution.",rules:["5 teams of at least 2 individuals per state","Must submit playable build and documentation","Judged on gameplay, creativity, and polish"],tips:["Keep gameplay focused and fun","Document your design decisions clearly","Test the game for usability and bugs"],participants:"5 teams of 2+ per state",duration:"Pre-event submission"},
  {id:39,type:"team",emoji:"🕶️",name:"Virtual Reality Simulation (VR)",tagline:"Create a VR experience that explores a STEM topic.",desc:"Teams design a VR simulation and submit supporting documentation on usability and technical design.",rules:["1 team per chapter; individual entries are permitted","Must submit VR project files and documentation","Judged on immersion, usability, and concept"],tips:["Design intuitive interactions for users","Keep VR experiences comfortable and easy to navigate","Explain your technical setup clearly"],participants:"1 team per chapter; individual entries permitted",duration:"Portfolio + demo"},
  {id:40,type:"team",emoji:"🌐",name:"Webmaster",tagline:"Develop a website that showcases a technology project or concept.",desc:"Teams build a website focused on usability, accessibility, and content quality.",rules:["1 team of at least 2 individuals per chapter","Must meet web design and accessibility standards","Judged on functionality, design, and content"],tips:["Use semantic HTML and clear navigation","Optimize for readability and quick loading","Include strong visual hierarchy and content organization"],participants:"1 team of 2+ per chapter",duration:"On-site website"},
];

const EVENT_RESOURCES = {
  8: [
    {
      title: 'Coding practice problem set',
      url: 'https://example.com/coding-practice',
      type: 'Practice',
      description: 'A set of sample coding problems with solutions to build speed and accuracy.'
    },
    {
      title: 'Official Coding rules',
      url: 'https://tsaweb.org/coding-rules',
      type: 'Guide',
      description: 'Use this page to confirm event rules, scoring, and allowed tools.'
    }
  ]
};

// Extracted the awards list to keep the UI logic clean (with the syntax comma fix included)
const HOME_AWARDS = [
  {name:'1st Place — Debating Technological Issues', detail:'Awarded for persuasive arguments, strong research, and confident delivery.'},
  {name:'1st Place — Future Technology and Engineering Teacher', detail:'Recognized for an outstanding lesson plan and strong educational presentation.'},
  {name:'1st Place — VR Visualization', detail:'Awarded for an immersive, innovative, and well-executed virtual experience.'},
  {name:'1st Place — Webmaster', detail:'Recognized for excellent web design, usability, and polished presentation.'},
  {name:'2nd Place — Audio Podcasting', detail:'Recognized for strong storytelling, production quality, and clear communication.'},
  {name:'2nd Place — Biotechnology Design', detail:'Awarded for a thoughtful, well-developed solution with strong scientific reasoning.'},
  {name:'2nd Place — Data Science and Analytics', detail:'Recognized for insightful analysis and strong data-driven conclusions.'},
  {name:'2nd Place — Software Development', detail:'Awarded for strong functionality, design, and presentation quality.'},
  {name:'2nd Place — Technology Bowl', detail:'Recognized for strong knowledge and quick, accurate responses.'},
  {name:'2nd Place — Video Game Design', detail:'Celebrated for creativity, gameplay quality, and overall execution.'},
  {name:'3rd Place — CAD Engineering', detail:'Celebrated for precision, technical detail, and polished presentation.'},
  {name:'3rd Place — Coding', detail:'Earned for efficient problem solving and strong programming execution.'},
  {name:'3rd Place — Forensic Science', detail:'Honored for careful analysis and accurate investigative reasoning.'},
  {name:'3rd Place — Geospatial Technology', detail:'Earned for clear spatial analysis and well-supported solutions.'}
];
